sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t aneesm1008/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true aneesm1008/docker-react-app npm run test -- -- coverage
